- hosts: webservers 
  become: True
  become_method: sudo
  tasks:
    - name: "Update Repository cache"
      apt:
          update_cache: true
          cache_valid_time: 3600
          force_apt_get: true
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: .
        dest: /var/www/html/demo/
